### ISSUE TITLE
Invalid anchor link if spaces exist in sub-titles

### ISSUE THREAD

**Issue by FeynmanZhou** [opencontainers/oci-conformance#104]
The anchor of [Azure Container Registry](https://conformance.opencontainers.org/#azurecontainerregistry) and [GitLab Container Registry](https://conformance.opencontainers.org/#gitlab) are not working on the website. If there is a space in the sub-title, the anchor link will be invalid.

**Comment by tianon** [comment]
_Technically_ this is a duplicate of https://github.com/opencontainers/oci-conformance/issues/88! :smile:

(Either way, now fixed :rocket:)
