### ISSUE TITLE
How do we motivate people to do peer verification?

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/oci-conformance#15]
A few ideas mentioned:
* Part of applying for certification includes committing to do peer verification for one (or two?) other products
* Scoreboard of peer verification participation

**Comment by hkamezawa** [comment]
Two peers sounds good but wait-for-review may cause starvation while people tend to have promise of shipment date to customers. So, I think we need some visualization like Kanban and some agile method (rules for the team) to run the team. Can LF  provide a scrum master ?

**Comment by stephenrwalli** [comment]
I was trying to consider this from an "abusive" perspective. Company A runs the tests and publishes results and awaits peer review. I think if it lags at all, Company A should be able to complain loudly to the Linux Foundation, OCI Trademark Board, Cert Working Group, or all of the above. I don't think we need to define a process at present, but this feels like a self-correcting problem from that perspective. 

If Company A runs the tests and publishes results and Company B contests the results in some manner, then Company A can again encourage another review or complain to the LF. If Company A was forcing a result (attempting an overly relaxed interpretation), then subsequent reviews from Company C will either support Company A or B and create enough of a question to force it back to the Cert Working Group. It then falls to the Cert Working Group to correct the problem. Again, I don't think this requires process yet. Even if there's collusion between bad actors, sooner or later a good actor will call the question and force it back onto the Linux Foundation, OCI Trademark Board, Cert Working Group.

**Comment by jdolitsky** [comment]
Going to close as outdated. Please re-open if more discussion necessary.
