### ISSUE TITLE
Integrate the certification program with CI?

### ISSUE THREAD

**Issue by liangchenye** [opencontainers/oci-conformance#33]
Hi,
I'm thinking of making the certification program more automatically. The demo is like this: https://github.com/liangchenye/oci-cert-demo, a runtime project could add the certification result icon to its README.md.

The detailed explaination is here:
https://github.com/opencontainers/runtime-tools/issues/527

**Comment by jdolitsky** [comment]
Going to close as outdated. Please re-open if more discussion necessary.
