### ISSUE TITLE
Mechanism for Certification of Products Before Public Announce

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/oci-conformance#4]
What privacy restrictions would we put in-place for certification of products before they are publicly announced?

**Comment by caniszczyk** [comment]
Some thoughts from today's OCI CertWG call:

* Organization bringing product can identify one OCI member organization that agrees to test confidentially
* OCI identifies one randomly selected OCI member organization from a pool of volunteers that agrees to test confidentially

**Comment by jdolitsky** [comment]
Going to close as outdated. Please re-open if more discussion necessary.
