### ISSUE TITLE
Example script looks for non-existent Dockerfile

### ISSUE THREAD

**Issue by amouat** [opencontainers/oci-conformance#42]
In the example script, the following line exists:

`cd tmp && docker build -t conformance:latest -f Dockerfile.conformance .`

For the distribution spec, the Dockerfile is called `Dockerfile`, not `Dockerfile.conformance`. I'm not sure if this should be changed in the script or if it would be better to rename the Dockerfile in the distribution-spec repo.

**Comment by amouat** [comment]
Ah, I think the problem is GitHub actions expect the name to be Dockerfile: https://github.com/opencontainers/distribution-spec/pull/98. So it might be best to change the script in this repo.

**Comment by jdolitsky** [comment]
ah yes, thank you. I think we are planning to move that Dockerfile into conformance directory, please see https://github.com/opencontainers/distribution-spec/issues/99

**Comment by jdolitsky** [comment]
Looks like this was fixed
