### ISSUE TITLE
Potential testing race conditions

### ISSUE THREAD

**Issue by shizhMSFT** [opencontainers/oci-conformance#52]
OCI-conformnace tests for all registry service providers are done via GitHub actions locating at [.github/workflows/](https://github.com/opencontainers/oci-conformance/tree/master/.github/workflows).

By looking through all the yaml files, all 4 tests against a single registry are conducted at the same time with the same repositories.
Taking [ACR](https://aka.ms/acr) as an example,
- `acr_1.yml` is scheduled at `0 6 * * *`, running against `ocitest`.
- `acr_2.yml` is scheduled at `0 6 * * *`, running against `ocitest`.
- `acr_3.yml` is scheduled at `0 6 * * *`, running against `ocitest`.
- `acr_4.yml` is scheduled at `0 6 * * *`, running against `ocitest`.

It is possible that `acr_2.yml` is running in the middle but some tags or blobs are removed by the tear down phase of other tests, causing false positive results.

Here are two options on the solutions.
1. Run tests against different `OCI_NAMESPACE` per test scenario.
2. Run tests at different times like
    - `0 6 * * *` for `*_1.yml`
    - `10 6 * * *` for `*_2.yml`
    - `20 6 * * *` for `*_3.yml`
    - `30 6 * * *` for `*_4.yml`

**Comment by shizhMSFT** [comment]
Option 1 is better since the tests may be triggered manually but it requires the registry service providers to offer more repositories.

**Comment by jdolitsky** [comment]
@shizhMSFT can you make a PR to this effect for ACR at https://github.com/opencontainers/oci-conformance (solution #1)?
