### ISSUE TITLE
conformance for django-oci

### ISSUE THREAD

**Issue by vsoch** [opencontainers/oci-conformance#63]
Hey there! Django-oci is a bit different than the registries I see here in that it's not an official service, it's something that a user can implement as a plugin in their own Django app. That said, I do run the complete conformance testing suite: https://vsoch.github.io/django-oci/conformance/. Is there a way that we can include it here? Maybe a different kind of group that is for plugins and similar that implement the OCI distribution spec?

**Comment by jdolitsky** [comment]
@vsoch - you might checkout how docker/distribution is being tested here:
https://github.com/opencontainers/oci-conformance/blob/master/.github/workflows/distribution_1.yml

You just want to add 4 github action .yml's (one for each worflow), then add an entry for django-oci under "Open Source" section here: https://github.com/opencontainers/oci-conformance/blob/master/distribution-spec/README.md

**Comment by vsoch** [comment]
I already have the test running as an action too https://github.com/vsoch/django-oci/blob/master/.github/workflows/main.yml#L78 to generate a single report, and the difference looks to be that you have it separated out into four reports? Is there any reason I can't just share one report, or do I have to artificially break them up?

**Comment by vsoch** [comment]
And it doesn't look like there is a way to specify the name / location of the report files... so I have to do some copy/rename foo.

**Comment by vsoch** [comment]
Can I just provide links to the same file? This is the most logical thing to do - the report includes all sections, my testing is currently doing all the section generation, and every section is represented in the report.html. The interested user can easily see the section of interest with control F. If the tests are meant to be run individually then it should be easier to do this, and a report generated for each (without all the grayed out sections and with a unique name).

**Comment by jdolitsky** [comment]
@vsoch - going to close this issue. The new process supports external runs. Please submit for django-oci based on https://github.com/opencontainers/oci-conformance/pull/78
